---
title: "Homework 5"
author: "Bingkun Luo"
date: "11/2/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(readr)
library(data.table)

```
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

### Problem 1

```{r}
str(iris_with_missing)


kable(head(iris_with_missing),format = "markdown")
```

```{r}
replace = function(x){
        if (class(x) == "numeric") {replace_na(x, mean(x, na.rm = TRUE))}       
        else if (class(x) == "character") {replace_na(x, "virginica")} 
                }

##apply using map

final_iris = map_df(iris_with_missing, replace)

kable(final_iris,format = "markdown",digits = 3)
```


### Problem 2

```{r}
input_files = list.files(path = './data/data', full.names = TRUE)


input_data = purrr::map_df(input_files, ~read.csv(.))

output_data = input_data%>%
       pivot_longer(week_1:week_8,
       names_to = "week",
       values_to = "data")%>%
       mutate(subject_id = c(rep("con_1",8),rep("con_2",8),
                     rep("con_3",8),rep("con_4",8),
                     rep("con_5",8),rep("con_6",8),rep("con_7",8),rep("con_8",8),
                     rep("con_9",8),rep("con_10",8),
                     rep("exp_1",8),rep("exp_2",8),rep("exp_3",8),rep("exp_4",8),
                     rep("exp_5",8),rep("exp_6",8),rep("exp_7",8),rep("exp_8",8),
                     rep("exp_9",8),rep("exp_10",8)),
              type = c(rep("control",80),rep("experiment",80)),
              type = as.factor(type))%>%
  group_by(week)

```


#### Graph
```{r}

ggplot(output_data ,aes(x = week, y = data, group = subject_id, color = type)) +
  geom_line() +
   labs(
    title = "Plot for control arm vs. experiment arm",
    x = "Observation time",
    y = "Data for arm",
    caption = "Data from zip")

```


### Problem 3


```{r}

simulate_fun = function(n,beta_0,beta_1,var){
  tibble(
  x = rnorm(n),
  y = beta_0+beta_1*x+rnorm(n,mean = 0,sd = sqrt(var)))
}


set.seed(1)
data_1 = rerun(10000, simulate_fun(30,2,0,50))
linear = map(data_1,~broom::tidy(lm(y~x, data = .)))

summary_1 =  data_1%>%
             tibble(linear,
                   beta_1 = 0,
                   estimate = map(linear, ~ .x[2,2]),
                   p_value = map(linear, ~ .x[2,5]))%>% 
             unnest(estimate:p_value) %>% 
             select(-linear)
  

summary_1


kable(head(summary_1),digits = 3)

  


```
```{r}
#data_2 = append(rerun(10000, simulate_fun(30,2,1,50)),
#              rerun(10000, simulate_fun(30,2,2,50)),
#              rerun(10000, simulate_fun(30,2,3,50)),
#              rerun(10000, simulate_fun(30,2,4,50)),
#              rerun(10000, simulate_fun(30,2,5,50)),
#              rerun(10000, simulate_fun(30,2,6,50)))

#linear = map(data_2,~broom::tidy(lm(y~x, data = .)))

#summary_2 =  data_1%>%
             #tibble(linear,
                #     beta_1 = c(rep(1,10000),rep(2,10000),rep(3,10000),
                #               rep(4,10000),rep(5,10000),rep(6,10000)),
                #   estimate = map(linear, ~ .x[2,2]),
                #  p_value = map(linear, ~ .x[2,5]))%>% 
            # unnest(estimate:p_value) %>% 
            # select(-linear)
  

#summary_2
```




```{r}
set.seed(1)


sim_regression = function(n, beta_0, beta_1,var,simulate_fun) {
    tibble(
      beta_1,
      sim_data =rerun(10000, simulate_fun(30,2,beta_1,50)),
      ls_fit = map(sim_data,~broom::tidy(lm(y ~ x, data = .))),
      estimate = map(ls_fit, ~ .x[2,2]),
      p_value = map(ls_fit, ~ .x[2,5]))%>% 
  unnest(estimate:p_value) %>% 
  select(-ls_fit)
  
}
      
beta_1 = list(1, 2, 3, 4, 5, 6)

sim_results = 
  map(beta_1, ~sim_regression(30,2,.x,50,simulate_fun))%>% 
  bind_rows()

  

```


```{r}

```



